name: ai
channels:
  - defaults
dependencies:
  - python=3.9
  - matplotlib=3.8.0
  - numpy=1.23.5
  - pandas=2.1.4
  - pip=23.3.1
  - scikit-learn=1.4.2
  - pomegranate=0.14.4
  - keras=2.10.0
  - tensorflow=2.10.0
  - xgboost=1.7.3
  - lightgbm=4.1.0
  - torchmetrics=1.1.2
  - torchvision=0.15.2
  - statsmodels=0.14.0
  - pip:
    - albumentations==1.4.2
    - torch==2.2.1
    - libauc==1.3.2
    - timm==0.9.16
