process:
  load_models: False
  load_timeseries_data: True
  perform_imputation: False
  perform_unit_conversion: False
  calculate_missing_params: False
  perform_ards_onset_detection: False
  perform_filtering: False
  perform_feature_selection: False
  perform_data_segregation: True 
  perform_timeseries_training: True
  perform_timeseries_classification: True
  perform_threshold_optimization: True
  calculate_evaluation_metrics: True
  perform_cross_validation: True
  save_models: False

  load_image_data: False
  train_image_models: False
  test_image_models: False

timeseries_models_to_execute:
  - Random_forest
  - XGBoost
  - AdaBoost

image_models_to_execute:
  - VisionTransformer

loading_paths:
  Random Forest: "default"
  Support Vector Machine: "Save/Cross validation results/Support Vector Machine_0"
  Bayesian Net: "Save/Cross validation results/Bayesian Net_3"
  Recurrent Neural Network: "Save/Cross validation results/Recurrent neural network_1"

storage_path: "Save/Result"




data:
  timeseries_file_path: "./Save/Result/uka_data_050623_preprocessed.csv" #"/hpcwork/rwth1474/Data/time_series/uka_data_050623.npy"
  database: "UKA"
  image_file_path: "Data/Image_data"
  pneumonia_dataset: "balanced"
  ards_dataset: "weighted"

processing:
  filtering:
    filter:
    - A
    - C

  imputation: 
    impute_empty_cells: True
    default_imputation_method: "forward"
    params_to_impute:
      - ards, forward
      - all

  params_to_calculate:
    - horovitz
  ards_onset_detection:
    detection_rule: "lowest_horovitz"
    #eventuell ver√§ndern.. bsp. lowest horowitz
    return_rule: "datapoint" 
    series_start_point: -50000
    series_end_point: 50000
    remove_ards_patients_without_onset: False
    impute_missing_rows: False
    update_ards_values: False

feature_selection:
  method: "univariate"
  variance: 0.16
  k: 15

data_segregation:
  training_test_ratio: 0.8
  percentage_of_ards_patients: None

evaluation:
  cross_validation:
    n_splits: 4
    shuffle: False
    random_state: 42
  threshold_optimization_algorithms: ["Standard", "MaxTPR", "MaxTPRMinFPR", "GeometricRoot"]
  evaluation_metrics: ["AUC", "Accuracy", "F1Score", "FPR", "MCC", "OptimalProbability", "Sensitivity", "Specificity", "TPR"]
  evaluation_name: "Evaluation X"

image_model_parameters:
  method: last_block
  mode: mode1
  num_epochs_pneumonia: 1
  num_epochs_ards: 1
  batch_size_pneumonia: 32
  batch_size_ards: 32
  SEED_pneumonia: 123
  SEED_ards: 105
  learning_rate: 0.05 
  k_folds: 2
  path: "Data/Image_data"