name: ml_framework_mac
channels:
  - defaults
  - conda-forge
  - inso
dependencies:
  - albumentations=1.3.1
  - h5py=3.9.0
  - keras=2.12.0
  - matplotlib=3.8.4
  - numpy=1.23.5
  - pandas=2.2.1
  - scikit-learn=1.4.2
  - tensorflow=2.12.0
  - pytorch=2.2.0
  - torchmetrics=1.1.2
  - yaml=0.2.5
  - py-xgboost=2.0.3
  - lightgbm=4.3.0
  - tqdm=4.66.2
  - timm=0.9.16
  - statsmodels=0.14.1
  - pip
  - pip:
    - pomegranate==0.14.8
    - opencv-python==4.8.0.74
